name: dl-env

channels: 
  - pytorch
  - conda-forge
  - default

dependencies:
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.6
  - opencv
  - libgcc
  - matplotlib
  - ipykernel
  - seaborn
  - albumentations
  - rasterio
  - pip
  - ipywidgets
  - pip:
    - kaggle
    - radiant_mlhub 
    - torchsummary
