name: dl-env

channels: 
  - pytorch
  - conda-forge
  - default

dependencies:
  - pytorch
  - torchvision
  - torchaudio
  - torchsummary
  - cudatoolkit=11.6
  - opencv
  - libgcc
  - matplotlib
  - ipykernel
  - seaborn
  - imgaug
  - albumentations
  - rasterio
  - ipywidgetsy
  pip:
    - kaggle
    - radiant_mlhub 
